name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_auth: ^0.15.0+1
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.12.10+2
  modal_progress_hud: ^0.1.3
  flutter_local_notifications: ^0.8.4+3
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  rxdart: ^0.22.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
